version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
    - .env.docker
    environment:
     - POSTGRES_DB=${POSTGRES_DB_NAME}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASS}
     - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
          - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
    - .env.docker
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql:
    image: mysql:5.7
    platform: "linux/amd64"
    env_file:
    - .env.docker
    environment:
     - MYSQL_DATABASE=${DATABASE_NAME}
     - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    ports:
      - '${DATABASE_PORT}:3306'
    volumes:
          - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: "linux/amd64"
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
     - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
volumes:
  postgres_data: {}
  mysql_data: {}
